name: 'ani-cli-mx shell checks'
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "ani-cli-mx"
      - "ani-cli-mx-core"

jobs:
  sh-checker:
    name: Shellcheck + Shfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run the sh-checker
      uses: luizm/action-sh-checker@master
      env:
        SHELLCHECK_OPTS: -s sh -o all -e 2250
        SHFMT_OPTS: -i 4 -ci -d
      
  check-exec:
    name: Executable Bit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: test exec bits
      run: test -x "./ani-cli-mx" && test -x "./ani-cli-mx-core"

  check-no-awk:
    name: No Awk Allowed
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: verify that no one added awk
      run: '! grep awk "./ani-cli-mx-core"'
